[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9"]

[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable", "pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmd = "pnpm run start"
