[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable", "pnpm install --filter=@repo/api"]

[phases.build]
cmds = ["pnpm run build --filter=@repo/api"]

[phases.start]
cmd = "pnpm start --filter=@repo/api"
